//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoGrupoPcSolucoes.Conexao
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int CodCliente { get; set; }
        public string NomFantasia { get; set; }
        public string RazaoSocial { get; set; }
        public string TipInscricao { get; set; }
        public string Cpf { get; set; }
        public string Cnpj { get; set; }
        public Nullable<System.DateTime> DtNacimento { get; set; }
        public Nullable<System.DateTime> DtAtividade { get; set; }
        public string Endereço { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Cep { get; set; }
        public string Fone { get; set; }
        public string Email { get; set; }
        
    }
    
}
